HostApplication/Models/ErrorViewModel.cs
namespace HostApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HostApplication/Controllers/EmbeddedApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using SharedComponents.Interfaces;
using SharedComponents.Models;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;

namespace HostApplication.Controllers
{
    public class EmbeddedApplicationController : Controller
    {

        private readonly EmbeddedAppConfiguration _embeddedAppConfiguration;
        private readonly JwtSettings _jwtSettings;
        private readonly HttpClient _httpClient;
        private readonly IHtmlParser _htmlParser;


        public EmbeddedApplicationController(
            IOptions<EmbeddedAppConfiguration> embeddedAppConfig,
            IOptions<JwtSettings> jwatSettings,
            HttpClient httpClient,
            IHtmlParser htmlParser)
        {
            _embeddedAppConfiguration = embeddedAppConfig.Value;
            _jwtSettings = jwatSettings.Value;
            _httpClient = httpClient;
            _htmlParser = htmlParser;
        }

        public IActionResult Index(string updateRelativeToAbsolutePath)
        {
            try
            {
                var embeddedAppSettings = new EmbeddedAppConfiguration
                {
                    EmbeddedAppBaseURL = _embeddedAppConfiguration.EmbeddedAppBaseURL,
                    ProxyURL = $"{Url.Content($"{_embeddedAppConfiguration.ProxyURL}")}?updateRelativeToAbsolutePath={Uri.EscapeDataString(updateRelativeToAbsolutePath)}",
                    Routes = _embeddedAppConfiguration.Routes,
                };

                return View(embeddedAppSettings);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<ActionResult> ProxyPage(string updateRelativeToAbsolutePath)
        {
            try
            {
                Guid userID = Guid.NewGuid();
                var jwt = GenerateJwtToken();

                var uriBuilder = new UriBuilder(_embeddedAppConfiguration.EmbeddedAppBaseURL)
                {
                    Path = _embeddedAppConfiguration.Routes.FirstOrDefault(r => r.API == "SingleSignOn")?.URL ?? string.Empty,
                    Query = $"updateRelativeToAbsolutePath={Uri.EscapeDataString(updateRelativeToAbsolutePath)}"
                };

                AddJWTTokenInHeader(jwt);

                string content = await GetWebPageContentOfEmbeddedApp(uriBuilder);

                content = await UpdatePathInHostingAppIfApplicable(updateRelativeToAbsolutePath, content);

                return Content(content, "text/html");
            }
            catch (HttpRequestException httpEx)
            {
                return StatusCode(500, $"HTTP error: {httpEx.Message}");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"An error occurred: {ex.Message}");
            }
        }

        [NonAction]
        private async Task<string> UpdatePathInHostingAppIfApplicable(string updateRelativeToAbsolutePath, string content)
        {
            if (updateRelativeToAbsolutePath.Equals(SharedComponents.Constants.AppConstants.UpdateRelativeToAbsolutePathInHostingApp))
            {
                content = await _htmlParser.ConvertRelativeToAbsoluteURL(html: content, baseUrl: _embeddedAppConfiguration.EmbeddedAppBaseURL);
            }

            return content;
        }

        [NonAction]
        private async Task<string> GetWebPageContentOfEmbeddedApp(UriBuilder uriBuilder)
        {
            var response = await _httpClient.GetAsync(uriBuilder.Uri);
            response.EnsureSuccessStatusCode();

            var content = await response.Content.ReadAsStringAsync();
            return content;
        }

        [NonAction]
        private void AddJWTTokenInHeader(string jwt)
        {
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwt);
        }

        [NonAction]
        private string GenerateJwtToken()
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_jwtSettings.SecretKey));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var descriptor = new SecurityTokenDescriptor
            {
                Issuer = "YourIssuer",
                Audience = "YourAudience",
                Expires = DateTime.UtcNow.AddMinutes(30),
                SigningCredentials = credentials,
                Subject = new ClaimsIdentity(new[]
                {
                new Claim(ClaimTypes.Name, "john_doe"),
                new Claim(ClaimTypes.Email, "john.doe@example.com"),
                new Claim(ClaimTypes.NameIdentifier, Guid.NewGuid().ToString()), // user ID
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()) // Token ID
                })
            };

            var handler = new JsonWebTokenHandler();
            return handler.CreateToken(descriptor);
        }

    }
}

HostApplication/Controllers/HomeController.cs
using HostApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HostApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HostApplication/Views/EmbeddedApplication/Index.cshtml
@model SharedComponents.Models.EmbeddedAppConfiguration
@{
    ViewBag.Title = "Index";
}


<header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-4">
    <div class="container-fluid px-4">
        <div class="page-header-content pt-4">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto">
                    <h5 class="page-header-title">
                        <span class="page-header-icon"><i data-feather="file-plus"></i></span>
                        Embedded Application
                    </h5>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main page content-->

<div class="container-fluid px-4 mt-n4">
    <div class="row">
        <div class="col-xxl">
            <div class="card mb-2">
                <div class="card-body px-2">
                    <div class="row">
                        <div class="col-12">
                            <iframe src='@Model.ProxyURL' style="width:100%;" height="800">
                            </iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HostApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HostApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HostApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HostApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@SharedComponents.Constants.AppConstants.HotingAppTitle</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmbeddedApplication" asp-action="Index" asp-route-updateRelativeToAbsolutePath="@SharedComponents.Constants.AppConstants.UpdateRelativeToAbsolutePathInEmbeddedApp">Embedded Application (Path Modified In Embedded App)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmbeddedApplication" asp-action="Index" asp-route-updateRelativeToAbsolutePath="@SharedComponents.Constants.AppConstants.UpdateRelativeToAbsolutePathInHostingApp">Embedded Application (Path Modified in Hosting App)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - HostApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>